In [4]:
import git
from pathlib import Path
import os

ROOT_DIR = Path(git.Repo('.', search_parent_directories=True).working_tree_dir)


In [ ]:
os.chdir(os.path.join(ROOT_DIR, "utilities"))
from transform import *
os.chdir(os.path.join(ROOT_DIR, "dataset-preparation"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\Users\\yashd\\Desktop\\hierarchical-bayesian-model-validation\\raw-data\\agriVision\\batch0-agriVision-RGB-cleaned'

In [141]:
x_3 = scipy.stats.norm.rvs(0, 3, size=2**6)# np.arange(0, 2**3)
x_6 = scipy.stats.norm.rvs(0, 3, size=2**20) # np.arange(0, 2**6)
x_9 = scipy.stats.laplace.rvs(0, scale=3, size=2**16)
x_9 = x_9.reshape((2**8, 2**8))

print(np.mean(x_3), np.var(x_3))
print(np.mean(x_6), np.var(x_6))
print(np.mean(x_9), np.var(x_9))

-0.12515990036993938 9.185418177914245
-0.002270965497774642 8.986770915881607
-0.013131685147534534 18.126064650685798


In [142]:
np.var(x_9)

np.float64(18.126064650685798)

In [143]:
pywt.wavedec2(x_9, wavelet='db1')[-1][0].shape

(128, 128)

In [145]:
np.var(pywt.wavedec2(x_9, wavelet='db1')[-1][0])

np.float64(18.185247541422633)

In [90]:

np.var(pywt.wavedec(x_6, wavelet='db1')[-3])

np.float64(6.968750792564551)

In [47]:
pywt.swt(x_3, level=1, wavelet='db1', norm=True)

[(array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 3.5]),
  array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  3.5]))]

In [49]:
pywt.swt(x_6, level=2, wavelet='db1', norm=True)

[(array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5,
         12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5,
         23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5,
         34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5,
         45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5, 55.5,
         56.5, 57.5, 58.5, 59.5, 60.5, 61.5, 46.5, 31.5, 16.5]),
  array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., 15., 31., 15.])),
 (array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
         11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
         22.5, 23.5, 24.5, 25.5, 26.5, 27.