In [1]:
import git
from pathlib import Path
import os

ROOT_DIR = Path(git.Repo('.', search_parent_directories=True).working_tree_dir)


In [2]:
os.chdir(os.path.join(ROOT_DIR, "utilities"))
from transform import *
os.chdir(os.path.join(ROOT_DIR, "dataset-preparation"))

In [9]:
x_3 = scipy.stats.norm.rvs(0, 3, size=2**6)# np.arange(0, 2**3)
x_6 = scipy.stats.norm.rvs(0, 3, size=2**20) # np.arange(0, 2**6)
x_9 = scipy.stats.laplace.rvs(0, scale=3, size=2**18)
x_9 = x_9.reshape((2**9, 2**9))

print(np.mean(x_3), np.var(x_3))
print(np.mean(x_6), np.var(x_6))
print(np.mean(x_9), np.var(x_9))

0.0348000893207996 9.133322249856759
0.004069323901649723 8.999878428228572
0.005368208323756714 17.92591546566788


In [10]:
np.var(x_9)

np.float64(17.92591546566788)

In [11]:
pywt.wavedec2(x_9, wavelet='db1')[-1][0].shape

(256, 256)

In [12]:
np.var(np.fft.fft2(x_9, norm='ortho'))

np.float64(17.925927044814806)

In [6]:
np.var(pywt.wavedec2(x_9, wavelet='db1')[-1][0])

np.float64(17.971572335871677)

In [7]:

np.var(pywt.wavedec(x_6, wavelet='db1')[-3])

np.float64(9.022568072042885)

In [47]:
pywt.swt(x_3, level=1, wavelet='db1', norm=True)

[(array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 3.5]),
  array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  3.5]))]

In [49]:
pywt.swt(x_6, level=2, wavelet='db1', norm=True)

[(array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5,
         12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5,
         23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5,
         34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5,
         45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5, 55.5,
         56.5, 57.5, 58.5, 59.5, 60.5, 61.5, 46.5, 31.5, 16.5]),
  array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., 15., 31., 15.])),
 (array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
         11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
         22.5, 23.5, 24.5, 25.5, 26.5, 27.